// examples/vite/src/App.tsx
import { useState } from 'react';
import reactLogo from './assets/react.svg';
import viteLogo from './assets/vite.svg';
import './App.css';

function App() {
  const [count, setCount] = useState(0);
  const runtime = window.__POWERED_BY_QIANKUN__ ? 'qiankun' : 'standalone';

  return (
    <main className="micro-shell">
      <header className="micro-header">
        <div className="logo-group">
          <a href="https://vite.dev" target="_blank" rel="noreferrer">
            <img src={viteLogo} className="logo" alt="Vite logo" />
          </a>
          <a href="https://react.dev" target="_blank" rel="noreferrer">
            <img src={reactLogo} className="logo react" alt="React logo" />
          </a>
        </div>
        <h1>Vite React Micro App</h1>
        <p>统一现代化子应用界面 · React Runtime</p>
      </header>

      <section className="card">
        <dl>
          <div>
            <dt>Framework</dt>
            <dd>React</dd>
          </div>
          <div>
            <dt>Bundler</dt>
            <dd>Vite 8</dd>
          </div>
          <div>
            <dt>Runtime</dt>
            <dd>{runtime}</dd>
          </div>
        </dl>

        <button type="button" onClick={() => setCount((value) => value + 1)}>
          Counter · {count}
        </button>
        <p className="hint">该应用展示 Vite 最新栈下的 qiankun 子应用挂载能力。</p>
      </section>
    </main>
  );
}

export default App;

// examples/vue/src/App.vue
<script setup lang="ts">
import { version } from 'vue'
import { ref } from 'vue'

const count = ref(0)
const increment = () => count.value++
</script>

<template>
  <div>
    <div>
      <a href="https://vite.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>

    <h1>Vue Micro App</h1>

    <div class="card">
      <div class="info-card">
        <p><strong>Vue Version:</strong> {{ version }}</p>
        <p><strong>Bundler:</strong> Vite</p>
        <p><strong>Running in:</strong> {{ (window as any).__POWERED_BY_QIANKUN__ ? 'qiankun' : 'standalone' }} mode</p>
      </div>

      <button type="button" @click="increment">count is {{ count }}</button>

      <p>
        This Vue micro-app is built with modern tools and can run both standalone and inside a qiankun main app.
      </p>
    </div>

    <p class="read-the-docs">
      Generated by create-qiankun
    </p>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

.card {
  padding: 2em;
}

.info-card {
  margin-bottom: 16px;
  padding: 12px;
  background-color: #f5f5f5;
  border-radius: 8px;
}

.info-card p {
  margin: 4px 0;
}

.read-the-docs {
  color: #888;
}
</style>
