// examples/webpack/src/App.tsx
import React, { useEffect, useRef, useState } from 'react';
import { messages, type Locale, type Messages } from './i18n';

const ACCENT = '#1C78C0';

declare global {
  interface Window {
    __SANDBOX_PROBE__?: string;
  }
}

/**
 * Where the shells fetch this app from: its own dev server locally, a path on the deployed site.
 * Defined by webpack.config.js off its `deployBase` env, the same value it pins publicPath to.
 */
declare const __MICRO_APP_ENTRY__: string;

function WindowProbe({ m }: { m: Messages }) {
  const [value, setValue] = useState<string>();

  const run = () => {
    window.__SANDBOX_PROBE__ = 'webpack-app:' + Date.now();
    setValue(window.__SANDBOX_PROBE__);
  };

  return (
    <div className="probe">
      <button className="control" onClick={run}>
        {m.writeGlobal}
      </button>
      <div className="probe-result">
        <code className="mono">{value ? `window.__SANDBOX_PROBE__ = '${value}'` : m.globalUndefined}</code>
        <p className="probe-note">{m.globalNote}</p>
      </div>
    </div>
  );
}

function TimerProbe({ m }: { m: Messages }) {
  const [ticks, setTicks] = useState<number>();
  const started = useRef(false);

  const run = () => {
    if (started.current) return;
    started.current = true;
    setTicks(0);
    // Deliberately never cleared — qiankun reclaims leaked timers on unmount.
    setInterval(() => setTicks((t) => (t ?? 0) + 1), 1000);
  };

  return (
    <div className="probe">
      <button className="control" onClick={run} disabled={started.current && ticks !== undefined}>
        {m.leakTimer}
      </button>
      <div className="probe-result">
        <code className="mono">{ticks === undefined ? m.noInterval : m.ticks(ticks)}</code>
        <p className="probe-note">{m.timerNote}</p>
      </div>
    </div>
  );
}

function StyleProbe({ m }: { m: Messages }) {
  const [injected, setInjected] = useState(false);

  useEffect(() => {
    return () => {
      document.head.querySelector('style[data-probe]')?.remove();
    };
  }, []);

  const run = () => {
    if (document.head.querySelector('style[data-probe]')) return;
    const style = document.createElement('style');
    style.setAttribute('data-probe', '');
    // body tints the whole page when standalone; under style isolation the body rule is
    // scoped away and only the app root (inside the @scope boundary) picks up the tint
    style.textContent = `body, .webpack-app { background: ${ACCENT}10 !important }`;
    document.head.appendChild(style);
    setInjected(true);
  };

  return (
    <div className="probe">
      <button className="control" onClick={run} disabled={injected}>
        {m.tintBody}
      </button>
      <div className="probe-result">
        <code className="mono">{injected ? m.tinted(`${ACCENT}10`) : m.noStyle}</code>
        <p className="probe-note">{m.styleNote}</p>
      </div>
    </div>
  );
}

export default function App({ locale = 'en' }: { locale?: Locale }) {
  const m = messages[locale];
  const [count, setCount] = useState(0);
  const insideQiankun = Boolean(window.__POWERED_BY_QIANKUN__);

  return (
    <div className="webpack-app">
      <header className="header">
        <span className="accent-dot" aria-hidden="true" />
        <h1 className="title">{m.title}</h1>
        <span className="badge mono">react {React.version}</span>
        <span className="badge mono">webpack 5 · classic</span>
        <span className={insideQiankun ? 'badge mono badge-accent' : 'badge mono'}>
          {insideQiankun ? m.insideQiankun : m.standalone}
        </span>
      </header>

      <section className="card">
        <h2 className="card-title">{m.isolationLab}</h2>
        <WindowProbe m={m} />
        <TimerProbe m={m} />
        <StyleProbe m={m} />
      </section>

      <section className="card">
        <h2 className="card-title">{m.localState}</h2>
        <div className="probe">
          <button className="control" onClick={() => setCount((c) => c + 1)}>
            {m.countIs(count)}
          </button>
          <div className="probe-result">
            <p className="probe-note">{m.stateNote}</p>
          </div>
        </div>
      </section>

      <footer className="footer mono">
        {m.entry} {__MICRO_APP_ENTRY__} · {m.lifecycle}: src/index.tsx
      </footer>
    </div>
  );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { computed, ref, version } from 'vue';
import { messages, type Locale } from './i18n';

const props = defineProps<{ hostProps?: Record<string, unknown> }>();

const ACCENT = '#42B883';

/**
 * Where the shells fetch this app from: its own dev server locally, a path on the deployed site
 * (`pages` is the mode `scripts/build-examples-site.mjs` builds with, and it sets Vite's base).
 */
const ENTRY = import.meta.env.MODE === 'pages' ? import.meta.env.BASE_URL : '//localhost:7101';

const poweredByQiankun = !!window.__POWERED_BY_QIANKUN__;

// the host's language arrives on the same props channel as everything else
const m = computed(() => messages[(props.hostProps?.locale as Locale | undefined) ?? 'en']);
const modeLabel = computed(() => (poweredByQiankun ? m.value.insideQiankun : m.value.standalone));

const probeValue = ref('');
const ticks = ref<number | null>(null);
const tinted = ref(false);
const count = ref(0);
let timerStarted = false;

const probeOutput = computed(() =>
  probeValue.value ? `window.__SANDBOX_PROBE__ = '${probeValue.value}'` : m.value.globalUnset,
);
const tickOutput = computed(() => (ticks.value === null ? m.value.noInterval : m.value.tick(ticks.value)));
const styleOutput = computed(() =>
  tinted.value ? m.value.styleInjected : m.value.noStyle,
);
// Echoed so a host driving the ui bindings' props channel can see its `update` land. qiankun mixes
// its own props in (container, singleSpa, mountParcel, …), so only the scalars the host set are shown.
const hostPropsOutput = computed(() => {
  const scalars = Object.entries(props.hostProps ?? {}).filter(
    ([, value]) => typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean',
  );
  return scalars.length ? scalars.map(([key, value]) => `${key}='${String(value)}'`).join(' ') : m.value.none;
});

function writeWindowProbe() {
  window.__SANDBOX_PROBE__ = 'vue:' + Date.now();
  probeValue.value = String(window.__SANDBOX_PROBE__);
}

function startTimerProbe() {
  if (timerStarted) return;
  timerStarted = true;
  ticks.value = 0;
  // deliberately never cleared — qiankun reclaims the leaked interval on unmount
  setInterval(() => {
    ticks.value = (ticks.value ?? 0) + 1;
  }, 1000);
}

function injectStyleProbe() {
  if (tinted.value) return;
  const style = document.createElement('style');
  style.dataset.probe = '';
  // body tints the whole page when standalone; under style isolation the body rule is
  // scoped away and only the app root (inside the @scope boundary) picks up the tint
  style.textContent = `body, .vue-app { background: ${ACCENT}18 !important }`;
  document.head.appendChild(style);
  tinted.value = true;
}
</script>

<template>
  <div class="vue-app">
    <header class="app-header">
      <span class="accent-dot" aria-hidden="true" />
      <h1>{{ m.title }}</h1>
      <div class="badges">
        <span class="badge">vue {{ version }}</span>
        <span class="badge">vite · esm</span>
        <span :class="poweredByQiankun ? 'badge badge-live' : 'badge'">{{ modeLabel }}</span>
      </div>
    </header>

    <section class="card">
      <h2>{{ m.isolationLab }}</h2>
      <div class="probe">
        <button type="button" @click="writeWindowProbe">{{ m.writeGlobal }}</button>
        <div class="probe-result">
          <output>{{ probeOutput }}</output>
          <p>{{ m.globalNote }}</p>
        </div>
      </div>
      <div class="probe">
        <button type="button" @click="startTimerProbe">{{ m.startInterval }}</button>
        <div class="probe-result">
          <output>{{ tickOutput }}</output>
          <p>{{ m.intervalNote }}</p>
        </div>
      </div>
      <div class="probe">
        <button type="button" @click="injectStyleProbe">{{ m.tintBody }}</button>
        <div class="probe-result">
          <output>{{ styleOutput }}</output>
          <p>{{ m.styleNote }}</p>
        </div>
      </div>
    </section>

    <section class="card">
      <h2>{{ m.localState }}</h2>
      <div class="counter">
        <button type="button" @click="count--">−</button>
        <span class="counter-value">{{ count }}</span>
        <button type="button" @click="count++">+</button>
        <p>{{ m.stateNote }}</p>
      </div>
    </section>

    <footer class="app-footer">
      {{ m.entry }} {{ ENTRY }} · {{ m.lifecycle }}: src/main.ts · {{ m.hostProps }}: {{ hostPropsOutput }}
    </footer>
  </div>
</template>

<style>
/* All rules scoped under .vue-app — no body/html rules here (design contract). */

.vue-app {
  --paper: #f7f8fa;
  --surface: #ffffff;
  --ink: #1b1f26;
  --ink-soft: #5c6470;
  --hairline: #e4e7ec;
  --primary: #6051a5;
  --accent: #42b883;
  --sans: 'IBM Plex Sans', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
  --mono: 'IBM Plex Mono', ui-monospace, monospace;
  --display: 'Space Grotesk', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;

  box-sizing: border-box;
  max-width: 720px;
  margin: 0 auto;
  padding: 40px 24px 32px;
  color: var(--ink);
  font-family: var(--sans);
  font-size: 15px;
  line-height: 1.5;
}

.vue-app *,
.vue-app *::before,
.vue-app *::after {
  box-sizing: inherit;
}

.vue-app .app-header {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 10px;
  margin-bottom: 20px;
}

.vue-app .accent-dot {
  flex: none;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: var(--accent);
}

.vue-app h1 {
  margin: 0;
  font-family: var(--display);
  font-size: 26px;
  font-weight: 600;
  line-height: 1.2;
  letter-spacing: -0.01em;
}

.vue-app .badges {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-left: auto;
}

.vue-app .badge {
  padding: 3px 8px;
  border: 1px solid var(--hairline);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink-soft);
  font-family: var(--mono);
  font-size: 12px;
  line-height: 1.4;
  white-space: nowrap;
}

.vue-app .badge-live {
  border-color: rgb(96 81 165 / 35%);
  color: var(--primary);
}

.vue-app .card {
  margin-bottom: 16px;
  padding: 18px 20px;
  border: 1px solid var(--hairline);
  border-radius: 10px;
  background: var(--surface);
}

.vue-app .card h2 {
  margin: 0 0 6px;
  font-size: 14px;
  font-weight: 600;
  color: var(--ink);
}

.vue-app .probe {
  display: grid;
  grid-template-columns: 180px 1fr;
  gap: 8px 20px;
  align-items: start;
  padding: 14px 0;
  border-bottom: 1px solid var(--hairline);
}

.vue-app .probe:last-of-type {
  padding-bottom: 4px;
  border-bottom: none;
}

.vue-app button {
  padding: 6px 12px;
  border: 1px solid var(--hairline);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
  font-family: var(--sans);
  font-size: 13px;
  font-weight: 500;
  line-height: 1.4;
  cursor: pointer;
  transition:
    border-color 160ms ease-out,
    color 160ms ease-out;
}

.vue-app button:hover {
  border-color: var(--accent);
  color: var(--accent);
}

@media (prefers-reduced-motion: reduce) {
  .vue-app button {
    transition: none;
  }
}

.vue-app .probe-result output {
  display: block;
  font-family: var(--mono);
  font-size: 13px;
  color: var(--ink);
  overflow-wrap: anywhere;
}

.vue-app .probe-result p {
  margin: 2px 0 0;
  font-size: 13px;
  color: var(--ink-soft);
}

.vue-app .counter {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 10px;
}

.vue-app .counter-value {
  min-width: 3ch;
  text-align: center;
  font-family: var(--mono);
  font-size: 22px;
  font-weight: 500;
}

.vue-app .counter p {
  margin: 0 0 0 8px;
  font-size: 13px;
  color: var(--ink-soft);
}

.vue-app .app-footer {
  margin-top: 20px;
  font-family: var(--mono);
  font-size: 12px;
  color: var(--ink-soft);
}
</style>
