// examples/vue/src/App.vue
<script setup lang="ts">
import { version } from 'vue'
import { ref } from 'vue'

const count = ref(0)
const increment = () => count.value++
</script>

<template>
  <div>
    <div>
      <a href="https://vite.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>

    <h1>Vue Micro App</h1>

    <div class="card">
      <div class="info-card">
        <p><strong>Vue Version:</strong> {{ version }}</p>
        <p><strong>Bundler:</strong> Vite</p>
        <p><strong>Running in:</strong> {{ (window as any).__POWERED_BY_QIANKUN__ ? 'qiankun' : 'standalone' }} mode</p>
      </div>

      <button type="button" @click="increment">count is {{ count }}</button>

      <p>
        This Vue micro-app is built with modern tools and can run both standalone and inside a qiankun main app.
      </p>
    </div>

    <p class="read-the-docs">
      Generated by create-qiankun
    </p>
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

.card {
  padding: 2em;
}

.info-card {
  margin-bottom: 16px;
  padding: 12px;
  background-color: #f5f5f5;
  border-radius: 8px;
}

.info-card p {
  margin: 4px 0;
}

.read-the-docs {
  color: #888;
}
</style>

// examples/react/src/App.tsx
import { useState, version } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>React Micro App</h1>

      <div className="card">
        <div style={{ marginBottom: '16px', padding: '12px', backgroundColor: '#f5f5f5', borderRadius: '8px' }}>
          <p><strong>React Version:</strong> {version}</p>
          <p><strong>Bundler:</strong> Vite</p>
          <p><strong>Running in:</strong> {(window as any).__POWERED_BY_QIANKUN__ ? 'qiankun' : 'standalone'} mode</p>
        </div>

        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>

        <p>
          This React micro-app is built with modern tools and can run both standalone and inside a qiankun main app.
        </p>
      </div>

      <p className="read-the-docs">
        Generated by create-qiankun
      </p>
    </>
  )
}

export default App
